CREATE TABLE `coin_tickers` (
	`coin_id` text NOT NULL,
	`exchange_id` text NOT NULL,
	`base` text NOT NULL,
	`target` text NOT NULL,
	`market_name` text NOT NULL,
	`last` real,
	`volume` real,
	`converted_last_usd` real,
	`converted_last_btc` real,
	`converted_volume_usd` real,
	`bid_ask_spread_percentage` real,
	`trust_score` text,
	`last_traded_at` integer,
	`last_fetch_at` integer,
	`is_anomaly` integer DEFAULT false NOT NULL,
	`is_stale` integer DEFAULT false NOT NULL,
	`trade_url` text,
	`token_info_url` text,
	`coin_gecko_url` text,
	PRIMARY KEY(`coin_id`, `exchange_id`, `base`, `target`),
	FOREIGN KEY (`coin_id`) REFERENCES `coins`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`exchange_id`) REFERENCES `exchanges`(`id`) ON UPDATE no action ON DELETE no action
);
